### ISSUE TITLE
Is it possibel to use marker.isDraggable = true ?

### ISSUE THREAD

**Issue by manoelsouzaunicef** [afanaian/GoogleMapsWithSwiftUISample#2]
I am trying to use the option marker.isDraggable = true ? But it never works. Can you recommend something?

**Comment by afanaian** [comment]
Which class are you trying to make it draggable? Did you drop your own pin?

**Comment by manoelsouzaunicef** [comment]
Hello! 
I made a mistake. I actually need to click and wait a few seconds to move the marker. I set the mark on the function
**makeUIView(context: Self.Context) -> GMSMapView** and work fine
